export const aboutSkills = [
    { title: 'HTML' },
    { title: 'CSS' },
    { title: 'JavaScript' },
    { title: 'SCSS' },
    { title: 'Tailwind CSS' },
    { title: 'React.js' },
    { title: 'Vite' },
    { title: 'Redux Toolkit' },
    { title: 'Webpack' },
    { title: 'TypeScript' },
    { title: 'Git' },
    { title: 'GitHub' },
    { title: 'Linux' },
];
