export const aboutSkills = [
    { title: 'HTML' },
    { title: 'CSS' },
    { title: 'Figma' },
    { title: 'JavaScript' },
    { title: 'SCSS' },
    { title: 'Tailwind CSS' },
    { title: 'shadcn' },
    { title: 'MaterialUI' },
    { title: 'ReactJS' },
    { title: 'Vite' },
    { title: 'NextJS' },
    { title: 'Redux Toolkit' },
    { title: 'React Query' },
    { title: 'TypeScript' },
    { title: 'Prisma' },
    { title: 'NodeJS' },
    { title: 'Express' },
    { title: 'Jest' },
    { title: 'Git' },
    { title: 'GitHub' },
    { title: 'Linux' },
];
