# Generated by Django 6.0.5 on 2026-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmenthistoryimages',
            name='development_history',
        ),
        migrations.RemoveField(
            model_name='project',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='DevelopmentHistory',
        ),
        migrations.DeleteModel(
            name='DevelopmentHistoryImages',
        ),
        migrations.DeleteModel(
            name='ProjectCapability',
        ),
        migrations.DeleteModel(
            name='ProjectFeature',
        ),
        migrations.DeleteModel(
            name='ProjectTool',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
