# Generated by Django 6.0.5 on 2026-07-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_developmenthistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmenthistory',
            options={'verbose_name': 'Development History', 'verbose_name_plural': 'Development Histories'},
        ),
        migrations.AlterModelOptions(
            name='projectcapability',
            options={'verbose_name': 'Project Capability', 'verbose_name_plural': 'Project Capabilities'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
