# Generated by Django 6.0.5 on 2026-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_developmenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmenthistoryicons',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='development_history_icons'),
        ),
    ]
