# Generated by Django 6.0.5 on 2026-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_developmenthistoryicons_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmenthistory',
            name='date_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='date_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
