# Generated by Django 6.0.5 on 2026-07-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_developmenthistory_date_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectcapability',
            name='capability_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcapability',
            name='capability_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='feature_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='feature_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
