# Generated by Django 6.0.5 on 2026-07-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmenthistory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='developmenthistory',
            name='title_ru',
        ),
    ]
