# Generated by Django 6.0.5 on 2026-07-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_developmenthistory_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcapability',
            old_name='capability',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projectcapability',
            old_name='capability_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='projectcapability',
            old_name='capability_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='projectfeature',
            old_name='feature',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projectfeature',
            old_name='feature_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='projectfeature',
            old_name='feature_ru',
            new_name='name_ru',
        ),
    ]
