# Generated by Django 6.0.5 on 2026-07-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_capability_projectcapability_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
    ]
