# Generated by Django 6.0.5 on 2026-07-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_projectimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmenthistory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
