# Generated by Django 6.0.5 on 2026-07-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_developmenthistory_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmenthistoryicons',
            options={'verbose_name': 'Development History Icon', 'verbose_name_plural': 'Development History Icons'},
        ),
    ]
