# Generated by Django 6.0.5 on 2026-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_developmenthistoryicons_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmenthistoryicons',
            name='development_history',
        ),
        migrations.AddField(
            model_name='developmenthistory',
            name='icons',
            field=models.ManyToManyField(blank=True, to='main.developmenthistoryicons'),
        ),
    ]
