# Generated by Django 6.0.5 on 2026-07-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
